void desenha_moldura();
void desenha_menu_superior(char itens_menu[][TAMANHO_STR]);
void desenha_menu_inferior(char itens_menu[][TAMANHO_STR], FAZENDEIRO fazendeiro, int num_cogumelos);
void desenha_jogador(FAZENDEIRO fazendeiro);
void desenha_tiros(TIRO tiros[], int num_tiros);
void desenha_cogumelos(COGUMELO cogumelos[], int num_cogumelos);
void desenha_ranking(JOGADOR jogadores[]);
void desenha_menu_pausa(char texto[], char input[]);
void desenha_aranhas(ARANHA aranhas[], int total_aranhas);
void desenha_milipede(MILIPEDE milipede);