void carrega_texturas(Texture2D texturas[]);
void descarrega_texturas(Texture2D texturas[]);
void desenha_moldura();
void desenha_menu_superior(char itens_menu[][TAMANHO_STR]);
void desenha_menu_inferior(char itens_menu[][TAMANHO_STR], FAZENDEIRO fazendeiro, int num_cogumelos);
void desenha_contador_doente(char itens[][TAMANHO_STR], FAZENDEIRO fazendeiro);
void desenha_jogador(FAZENDEIRO fazendeiro, Texture2D textura);
void desenha_tiros(TIRO tiros[], int num_tiros);
void desenha_cogumelos(COGUMELO cogumelos[], int num_cogumelos, Texture2D textura);
void desenha_ranking(JOGADOR jogadores[]);
void desenha_menu_pausa(char texto[], char input[]);
void desenha_aranhas(ARANHA aranhas[], int total_aranhas, Texture2D textura);
void desenha_milipede(MILIPEDE milipede, Texture2D textura_cabeca, Texture2D textura_corpo);
